name: Build and Publish to Raspberry

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Configura QEMU (emulatore per compilare per ARM)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. Configura Docker Buildx (strumento di build avanzato)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login su Docker Hub (o GHCR)
      # Devi impostare i secrets DOCKER_USERNAME e DOCKER_PASSWORD su GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build e Push del BACKEND (Multi-arch)
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./back-end/Dockerfile # Percorso del dockerfile backend
          push: true
          # Qui specifichi che vuoi un'immagine che funzioni su PC e Raspberry (arm64)
          platforms: linux/amd64,linux/arm64 
          tags: gianlucaascari1/spaguette-app-backend:latest

      # 5. Build e Push del FRONTEND (Multi-arch)
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./front-end/Dockerfile # Percorso del dockerfile frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: gianlucaascari1/spaguette-app-frontend:latest